require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe MentorsController, type: :controller do
  before(:all) do
    @school1 = School.find_by(name: 'Berkeley Arts Magnet School') || create(:school)
    @admin1 =  Admin.find_by(email: 'adminrspec@superspec.berkeley.edu') || create(:admin)
    @super1 =  Super.find_by(email: 'superspec1@superspec.berkeley.edu') || create(:super, :name => 'rspec1', :email => 'superspec1@superspec.berkeley.edu')
  end
  # This should return the minimal set of attributes required to create a valid
  # Mentor. As you add validations to Mentor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {name:'Mentor Test', email:'fmentortest@berkeley.edu', school: @school1}
  }

  let(:invalid_attributes) {
    {name:'Me', email:'fmentortest@berkeley.edu', school: 'Berkeley Arts Magnet School'}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MentorsController. Be sure to keep this updated too.
  let(:valid_session) { {:email_address => @super1.email} }

  describe "GET #_index" do
    it "returns a success response" do
      Mentor.create! valid_attributes
      get :_index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      mentor = Mentor.create! valid_attributes
      get :show, params: {id: mentor.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      mentor = Mentor.create! valid_attributes
      get :edit, params: {id: mentor.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Mentor" do
        expect {
          post :create, params: {mentor: {name:'Mentor Test B', email:'fmentortestB@berkeley.edu', school_id: @school1.id}}, session: valid_session
        }.to change(Mentor, :count).by(1)
      end

      it "redirects to the creator" do
        post :create, params: {mentor: valid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {mentor: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {name:'Mentor Test Updated', email:'fmentortest@berkeley.edu', school: 'Berkeley Arts Magnet School'}
      }

      it "updates the requested mentor" do
        mentor = Mentor.create! valid_attributes
        put :update, params: {id: mentor.to_param, mentor: new_attributes}, session: valid_session
        mentor.reload
        expect(mentor.name).to eq(new_attributes[:name])
      end

      it "redirects to the creator" do
        mentor = Mentor.create! valid_attributes
        put :update, params: {id: mentor.to_param, mentor: valid_attributes}, session: valid_session
        expect(response).to redirect_to(@super1)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        mentor = Mentor.create! valid_attributes
        put :update, params: {id: mentor.to_param, mentor: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested mentor" do
      mentor = Mentor.create! valid_attributes
      expect {
        delete :destroy, params: {id: mentor.to_param}, session: valid_session
      }.to change(Mentor, :count).by(-1)
    end

    it "redirects to the mentors list" do
      mentor = Mentor.create! valid_attributes
      delete :destroy, params: {id: mentor.to_param}, session: valid_session
      expect(response).to redirect_to(@super1)
    end
  end

end
