require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe SchoolsController, type: :controller do
  before(:each) do
    @super1 =  Super.find_by(email: 'superspec1@superspec.berkeley.edu') || create(:super, :name => 'rspec1', :email => 'superspec1@superspec.berkeley.edu')
    @school1= School.find_by(address: '2015 Virginia St, Berkeley, CA 94709') || create(:school)
    @school1.destroy
  end

  # This should return the minimal set of attributes required to create a valid
  # School. As you add validations to School, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {{
    name:'Berkeley Arts Magnet School',
    address:'2015 Virginia St, Berkeley, CA 94709',
    lat: 37.876869,
    lon:-122.270348
  }}

  let(:invalid_attributes) {{
    name:'Be',
    address:'2015 Virginia St, Berkeley, CA 94709-+@!',
    lat: 37.876869,
    lon:-122.270348
  }}

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SchoolsController. Be sure to keep this updated too.
  let(:valid_session) { {:email_address => @super1.email} }

  describe "GET #_index" do
    it "returns a success response" do
      school = create(:school)
      get :_index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      school = create(:school)
      get :show, params: {id: school.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      school = School.create! valid_attributes
      get :edit, params: {id: school.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new School" do
        expect {
          post :create, params: {school: valid_attributes}, session: valid_session
        }.to change(School, :count).by(1)
      end

      it "redirects back to the super user" do
        post :create, params: {school: valid_attributes}, session: valid_session
        expect(response).to redirect_to(@super1)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {school: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {{
        name: 'The Updated Berkeley Arts Magnet School',
        address:'2015 Virginia St, Berkeley, CA 94709',
        lat: 37.876869,
        lon:-122.270348
      }}

      it "updates the requested school" do
        school = School.create! valid_attributes
        put :update, params: {id: school.to_param, school: new_attributes}, session: valid_session
        school.reload
        expect(school.name).to eq(new_attributes[:name])
      end

      it "redirects to the school" do
        school = School.create! valid_attributes
        put :update, params: {id: school.to_param, school: valid_attributes}, session: valid_session
        expect(response).to redirect_to(@super1)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        school = School.create! valid_attributes
        put :update, params: {id: school.to_param, school: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested school" do
      school = School.create! valid_attributes
      expect {
        delete :destroy, params: {id: school.to_param}, session: valid_session
      }.to change(School, :count).by(-1)
    end

    it "redirects to the schools list" do
      school = School.create! valid_attributes
      delete :destroy, params: {id: school.to_param}, session: valid_session
      expect(response).to redirect_to(@super1)
    end
  end

end
